"use client";

import { useEffect, useState, useMemo } from "react";
import { useOrg } from "@/lib/context/org-context";
import { createClient } from "@/lib/supabase/client";
import type { Profile, TimeEntry, Standup, DailyPromise } from "@/lib/types/database";
import { CATEGORIES } from "@/lib/constants";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { cn, getInitials, getTodayMTY, formatHour } from "@/lib/utils";
import { format, subDays } from "date-fns";
import { es } from "date-fns/locale";
import {
  Bot, CheckCircle2, Pencil, AlertTriangle, MessageSquare,
  ChevronDown, ChevronUp, TrendingUp, TrendingDown,
} from "lucide-react";

// ═══════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════

interface StandupWithProfile extends Standup {
  profiles: Profile;
}

interface MemberCompliance {
  userId: string;
  fullName: string;
  avatarUrl: string | null;
  standupCount: number;
  totalDays: number;
  rate: number;
}

// ═══════════════════════════════════════════════════════════
// Auto-generate standup from entries
// ═══════════════════════════════════════════════════════════

function generateStandup(
  entries: TimeEntry[],
  promises: DailyPromise[],
): { yesterday: string; todayPlan: string; blockers: string } {
  // AYER section
  const sorted = [...entries].sort((a, b) => a.hour - b.hour);
  const lines = sorted.map((e) => {
    const cat = CATEGORIES[e.category];
    return `[${cat?.emoji ?? "--"}] ${e.title} (${formatHour(e.hour)})`;
  });

  const totalHours = entries.length;
  const withProof = entries.filter(
    (e) => (e.proof_urls && e.proof_urls.length > 0) || (e.links && e.links.length > 0),
  ).length;
  const proofPct = totalHours > 0 ? Math.round((withProof / totalHours) * 100) : 0;

  let yesterday: string;
  if (lines.length === 0) {
    yesterday = "Sin entradas registradas ayer.";
  } else {
    yesterday =
      lines.join("\n") +
      `\n\nTotal: ${totalHours} hora${totalHours !== 1 ? "s" : ""}, ${proofPct}% con evidencia`;
  }

  // HOY section
  let todayPlan: string;
  if (promises.length > 0) {
    todayPlan = promises.map((p) => `- ${p.title}`).join("\n");
  } else {
    todayPlan = "Pendiente de definir";
  }

  // BLOCKERS section
  const blocked = entries.filter((e) => e.category === "blocked");
  let blockers: string;
  if (blocked.length > 0) {
    blockers = blocked
      .map((e) => `- ${e.title}${e.blocker_detail ? `: ${e.blocker_detail}` : ""}`)
      .join("\n");
  } else {
    blockers = "Sin bloqueadores reportados";
  }

  return { yesterday, todayPlan, blockers };
}

// ═══════════════════════════════════════════════════════════
// Page
// ═══════════════════════════════════════════════════════════

export default function AutoStandupPage() {
  const { orgId, userId, loading: orgLoading } = useOrg();
  const supabase = createClient();
  const today = getTodayMTY();
  const yesterday = subDays(new Date(today + "T12:00:00"), 1).toISOString().split("T")[0];

  // ── State ──
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [myStandup, setMyStandup] = useState<StandupWithProfile | null>(null);
  const [teamStandups, setTeamStandups] = useState<StandupWithProfile[]>([]);
  const [members, setMembers] = useState<(Profile & { user_id: string })[]>([]);
  const [yesterdayEntries, setYesterdayEntries] = useState<TimeEntry[]>([]);
  const [todayPromises, setTodayPromises] = useState<DailyPromise[]>([]);
  const [complianceData, setComplianceData] = useState<MemberCompliance[]>([]);

  // Auto-generated content
  const [yesterdayText, setYesterdayText] = useState("");
  const [todayPlanText, setTodayPlanText] = useState("");
  const [blockersText, setBlockersText] = useState("");
  const [autoGenerated, setAutoGenerated] = useState({ yesterday: "", todayPlan: "", blockers: "" });
  const [showCompliance, setShowCompliance] = useState(false);

  const isEdited = useMemo(() => {
    return (
      yesterdayText !== autoGenerated.yesterday ||
      todayPlanText !== autoGenerated.todayPlan ||
      blockersText !== autoGenerated.blockers
    );
  }, [yesterdayText, todayPlanText, blockersText, autoGenerated]);

  // ── Load data ──
  useEffect(() => {
    if (orgLoading) return;
    if (!orgId || !userId) {
      setLoading(false);
      return;
    }

    async function load() {
      const fourteenDaysAgo = subDays(new Date(today + "T12:00:00"), 14)
        .toISOString()
        .split("T")[0];

      const [
        standupRes,
        entriesRes,
        promisesRes,
        membersRes,
        complianceRes,
      ] = await Promise.all([
        // Today's standups for team
        supabase
          .from("standups")
          .select("*, profiles(*)")
          .eq("org_id", orgId!)
          .eq("date", today)
          .order("submitted_at", { ascending: true }),
        // Yesterday's entries for current user
        supabase
          .from("time_entries")
          .select("*")
          .eq("user_id", userId!)
          .eq("org_id", orgId!)
          .eq("date", yesterday)
          .order("hour", { ascending: true }),
        // Today's promises for current user
        supabase
          .from("daily_promises")
          .select("*")
          .eq("user_id", userId!)
          .eq("org_id", orgId!)
          .eq("date", today),
        // All org members
        supabase
          .from("org_members")
          .select("user_id, profiles(*)")
          .eq("org_id", orgId!),
        // Last 14 days of standups for compliance
        supabase
          .from("standups")
          .select("user_id, date")
          .eq("org_id", orgId!)
          .gte("date", fourteenDaysAgo)
          .lte("date", today),
      ]);

      const allStandups = (standupRes.data ?? []) as unknown as StandupWithProfile[];
      const mine = allStandups.find((s) => s.user_id === userId);
      setMyStandup(mine ?? null);
      setTeamStandups(allStandups);

      const entries = (entriesRes.data ?? []) as TimeEntry[];
      setYesterdayEntries(entries);

      const promises = (promisesRes.data ?? []) as DailyPromise[];
      setTodayPromises(promises);

      // Parse members
      const membersList = (membersRes.data ?? []).map((m: any) => ({
        ...m.profiles,
        user_id: m.user_id,
      }));
      setMembers(membersList);

      // Calculate compliance per member (last 14 days, excluding weekends)
      const complianceStandups = complianceRes.data ?? [];
      const standupMap = new Map<string, Set<string>>();
      for (const s of complianceStandups) {
        if (!standupMap.has(s.user_id)) standupMap.set(s.user_id, new Set());
        standupMap.get(s.user_id)!.add(s.date);
      }

      // Count weekdays in last 14 days
      let weekdays = 0;
      for (let i = 0; i < 14; i++) {
        const d = subDays(new Date(today + "T12:00:00"), i);
        const dow = d.getDay();
        if (dow !== 0 && dow !== 6) weekdays++;
      }

      const compliance: MemberCompliance[] = membersList.map((m: any) => {
        const count = standupMap.get(m.user_id)?.size ?? 0;
        return {
          userId: m.user_id,
          fullName: m.full_name ?? m.email ?? "?",
          avatarUrl: m.avatar_url,
          standupCount: count,
          totalDays: weekdays,
          rate: weekdays > 0 ? Math.round((count / weekdays) * 100) : 0,
        };
      });
      compliance.sort((a, b) => b.rate - a.rate);
      setComplianceData(compliance);

      // Auto-generate if no standup exists
      if (!mine) {
        const gen = generateStandup(entries, promises);
        setYesterdayText(gen.yesterday);
        setTodayPlanText(gen.todayPlan);
        setBlockersText(gen.blockers);
        setAutoGenerated(gen);
      }

      setLoading(false);
    }

    load();
  }, [orgLoading, orgId, userId]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Submit standup ──
  async function handleSubmit() {
    if (!userId || !orgId) return;
    setSubmitting(true);

    const { data } = await supabase
      .from("standups")
      .upsert(
        {
          user_id: userId,
          org_id: orgId,
          date: today,
          yesterday: yesterdayText,
          today_plan: todayPlanText,
          blockers: blockersText || null,
          mood: null,
        },
        { onConflict: "user_id,org_id,date" },
      )
      .select("*, profiles(*)")
      .single();

    if (data) {
      const standup = data as unknown as StandupWithProfile;
      setMyStandup(standup);
      setTeamStandups((prev) => {
        const filtered = prev.filter((s) => s.user_id !== userId);
        return [...filtered, standup];
      });
    }
    setSubmitting(false);
  }

  // ── Members without standup ──
  const membersWithout = useMemo(() => {
    const standupUserIds = new Set(teamStandups.map((s) => s.user_id));
    return members.filter((m) => !standupUserIds.has(m.user_id));
  }, [members, teamStandups]);

  const bestCompliance = complianceData[0];
  const worstCompliance = complianceData[complianceData.length - 1];

  const displayDate = format(new Date(today + "T12:00:00"), "EEEE, d MMMM yyyy", { locale: es });

  // ── Loading ──
  if (loading || orgLoading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="animate-pulse text-muted-foreground font-mono text-xs tracking-widest uppercase">
          Cargando...
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8">
      {/* ── Header ── */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-1">
          <Bot className="w-5 h-5 text-primary" />
          <h1 className="text-xl font-mono font-bold tracking-tight uppercase">
            Auto-Standup
          </h1>
        </div>
        <p className="text-muted-foreground text-xs font-mono capitalize">{displayDate}</p>
        <p className="text-muted-foreground text-[10px] font-mono mt-1 tracking-wide">
          Claude lee tus entradas de ayer y escribe tu standup. Solo revisa y confirma.
        </p>
      </div>

      {/* ── Already submitted ── */}
      {myStandup ? (
        <div className="mb-8">
          <div className="border border-green-600/30 bg-green-500/5 p-4 flex items-center gap-3">
            <CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" />
            <div>
              <p className="text-sm font-mono font-medium text-green-600">
                Ya completaste tu standup
              </p>
              <p className="text-[10px] font-mono text-muted-foreground mt-0.5">
                Enviado a las {format(new Date(myStandup.submitted_at), "h:mm a")}
              </p>
            </div>
          </div>

          {/* Show submitted standup */}
          <div className="border border-border mt-4 p-4 space-y-4">
            <div>
              <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground mb-1">
                AYER
              </p>
              <pre className="text-xs font-mono whitespace-pre-wrap text-foreground leading-relaxed">
                {myStandup.yesterday}
              </pre>
            </div>
            <div>
              <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground mb-1">
                HOY
              </p>
              <pre className="text-xs font-mono whitespace-pre-wrap text-foreground leading-relaxed">
                {myStandup.today_plan}
              </pre>
            </div>
            {myStandup.blockers && (
              <div>
                <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-red-500 mb-1">
                  BLOQUEADORES
                </p>
                <pre className="text-xs font-mono whitespace-pre-wrap text-red-600 dark:text-red-400 leading-relaxed">
                  {myStandup.blockers}
                </pre>
              </div>
            )}
          </div>
        </div>
      ) : (
        /* ── Auto-generated standup form ── */
        <div className="mb-8">
          {/* Status badge */}
          <div className="flex items-center gap-2 mb-4">
            {isEdited ? (
              <Badge
                variant="outline"
                className="font-mono text-[10px] tracking-wide border-amber-500/40 text-amber-600"
              >
                <Pencil className="w-3 h-3 mr-1" />
                Editado
              </Badge>
            ) : (
              <Badge
                variant="outline"
                className="font-mono text-[10px] tracking-wide border-primary/40 text-primary"
              >
                <Bot className="w-3 h-3 mr-1" />
                Auto-generado por Claude
              </Badge>
            )}
            {yesterdayEntries.length === 0 && (
              <Badge
                variant="outline"
                className="font-mono text-[10px] tracking-wide border-red-500/40 text-red-500"
              >
                <AlertTriangle className="w-3 h-3 mr-1" />
                Sin entradas de ayer
              </Badge>
            )}
          </div>

          {/* AYER */}
          <div className="mb-4">
            <label className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground block mb-2">
              AYER
            </label>
            <Textarea
              value={yesterdayText}
              onChange={(e) => setYesterdayText(e.target.value)}
              className="font-mono text-xs min-h-[120px] resize-y"
              placeholder="Auto-generado a partir de tus entradas de ayer..."
            />
          </div>

          {/* HOY */}
          <div className="mb-4">
            <label className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground block mb-2">
              HOY
            </label>
            <Textarea
              value={todayPlanText}
              onChange={(e) => setTodayPlanText(e.target.value)}
              className="font-mono text-xs min-h-[80px] resize-y"
              placeholder="Plan del día..."
            />
          </div>

          {/* BLOQUEADORES */}
          <div className="mb-6">
            <label className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground block mb-2">
              BLOQUEADORES
            </label>
            <Textarea
              value={blockersText}
              onChange={(e) => setBlockersText(e.target.value)}
              className="font-mono text-xs min-h-[60px] resize-y"
              placeholder="Problemas o bloqueos..."
            />
          </div>

          {/* Submit */}
          <Button
            onClick={handleSubmit}
            disabled={submitting || !yesterdayText.trim()}
            className="w-full font-mono text-xs uppercase tracking-wide"
          >
            {submitting ? "Enviando..." : "Confirmar Standup"}
          </Button>
        </div>
      )}

      {/* ── Team standups ── */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground">
            Equipo &mdash; {teamStandups.length} standup{teamStandups.length !== 1 ? "s" : ""} hoy
          </h2>
        </div>

        {/* Members without standup */}
        {membersWithout.length > 0 && (
          <div className="border border-red-500/20 bg-red-500/5 p-3 mb-4">
            <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-red-500 mb-2">
              SIN STANDUP
            </p>
            <div className="flex flex-wrap gap-2">
              {membersWithout.map((m) => (
                <div
                  key={m.user_id}
                  className="flex items-center gap-2 bg-red-500/10 border border-red-500/20 px-2 py-1"
                >
                  <Avatar className="w-5 h-5 ring-1 ring-border">
                    <AvatarImage src={m.avatar_url ?? undefined} />
                    <AvatarFallback className="text-[8px] font-mono">
                      {getInitials(m.full_name)}
                    </AvatarFallback>
                  </Avatar>
                  <span className="text-[10px] font-mono font-medium text-red-600 dark:text-red-400">
                    {m.full_name ?? m.email ?? "?"}
                  </span>
                  <Badge
                    variant="destructive"
                    className="font-mono text-[8px] px-1 py-0"
                  >
                    SIN STANDUP
                  </Badge>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Submitted standups */}
        {teamStandups.length === 0 ? (
          <div className="border border-border p-8 flex flex-col items-center justify-center">
            <div className="w-16 h-16 border border-border flex items-center justify-center mb-4">
              <MessageSquare className="w-8 h-8 text-muted-foreground" />
            </div>
            <p className="text-muted-foreground text-xs font-mono">
              Nadie ha hecho su standup todavía.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {teamStandups.map((s) => (
              <div
                key={s.id}
                className="border border-border transition-colors duration-200 hover:border-primary/30 p-4"
              >
                <div className="flex items-center gap-3 mb-3">
                  <Avatar className="w-7 h-7 ring-1 ring-border">
                    <AvatarImage src={s.profiles?.avatar_url ?? undefined} />
                    <AvatarFallback className="text-[9px] font-mono">
                      {getInitials(s.profiles?.full_name)}
                    </AvatarFallback>
                  </Avatar>
                  <div className="flex-1 min-w-0">
                    <p className="font-mono text-xs font-medium truncate">
                      {s.profiles?.full_name ?? "?"}
                    </p>
                    <p className="text-[9px] font-mono text-muted-foreground">
                      {format(new Date(s.submitted_at), "h:mm a")}
                    </p>
                  </div>
                  {s.user_id === userId && (
                    <Badge
                      variant="outline"
                      className="font-mono text-[8px] border-primary/30 text-primary"
                    >
                      TÚ
                    </Badge>
                  )}
                </div>

                <div className="space-y-2">
                  <div>
                    <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground mb-0.5">
                      AYER
                    </p>
                    <pre className="text-[11px] font-mono whitespace-pre-wrap text-foreground/90 leading-relaxed">
                      {s.yesterday}
                    </pre>
                  </div>
                  <div>
                    <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground mb-0.5">
                      HOY
                    </p>
                    <pre className="text-[11px] font-mono whitespace-pre-wrap text-foreground/90 leading-relaxed">
                      {s.today_plan}
                    </pre>
                  </div>
                  {s.blockers && (
                    <div>
                      <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-red-500 mb-0.5">
                        BLOQUEADORES
                      </p>
                      <pre className="text-[11px] font-mono whitespace-pre-wrap text-red-600 dark:text-red-400 leading-relaxed">
                        {s.blockers}
                      </pre>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ── Compliance stats ── */}
      <div className="mb-8">
        <button
          onClick={() => setShowCompliance(!showCompliance)}
          className="flex items-center gap-2 w-full text-left mb-4 group"
        >
          <h2 className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground">
            Cumplimiento Standup (14 días)
          </h2>
          {showCompliance ? (
            <ChevronUp className="w-3 h-3 text-muted-foreground" />
          ) : (
            <ChevronDown className="w-3 h-3 text-muted-foreground" />
          )}
        </button>

        {showCompliance && complianceData.length > 0 && (
          <>
            {/* Best / Worst */}
            <div className="grid grid-cols-2 gap-3 mb-4">
              {bestCompliance && (
                <div className="bg-accent/30 border border-border p-3">
                  <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground mb-1">
                    Más cumplido
                  </p>
                  <div className="flex items-center gap-2">
                    <TrendingUp className="w-3.5 h-3.5 text-green-600" />
                    <span className="font-mono text-xs font-medium truncate">
                      {bestCompliance.fullName}
                    </span>
                  </div>
                  <p className="font-mono text-lg tabular-nums tracking-tight text-green-600 mt-1">
                    {bestCompliance.rate}%
                  </p>
                </div>
              )}
              {worstCompliance && complianceData.length > 1 && (
                <div className="bg-accent/30 border border-border p-3">
                  <p className="font-mono text-[9px] tracking-[0.18em] uppercase text-muted-foreground mb-1">
                    Menos cumplido
                  </p>
                  <div className="flex items-center gap-2">
                    <TrendingDown className="w-3.5 h-3.5 text-red-500" />
                    <span className="font-mono text-xs font-medium truncate">
                      {worstCompliance.fullName}
                    </span>
                  </div>
                  <p className="font-mono text-lg tabular-nums tracking-tight text-red-500 mt-1">
                    {worstCompliance.rate}%
                  </p>
                </div>
              )}
            </div>

            {/* Full list */}
            <div className="border border-border divide-y divide-border">
              {complianceData.map((c) => (
                <div key={c.userId} className="flex items-center gap-3 p-3">
                  <Avatar className="w-6 h-6 ring-1 ring-border">
                    <AvatarImage src={c.avatarUrl ?? undefined} />
                    <AvatarFallback className="text-[8px] font-mono">
                      {getInitials(c.fullName)}
                    </AvatarFallback>
                  </Avatar>
                  <span className="font-mono text-xs font-medium flex-1 truncate">
                    {c.fullName}
                  </span>
                  <span className="font-mono text-[10px] text-muted-foreground tabular-nums">
                    {c.standupCount}/{c.totalDays}
                  </span>
                  <div className="w-16 h-1.5 bg-accent/40 overflow-hidden">
                    <div
                      className={cn(
                        "h-full transition-all",
                        c.rate >= 80
                          ? "bg-green-500"
                          : c.rate >= 50
                            ? "bg-amber-500"
                            : "bg-red-500",
                      )}
                      style={{ width: `${c.rate}%` }}
                    />
                  </div>
                  <span
                    className={cn(
                      "font-mono text-xs tabular-nums tracking-tight font-medium w-10 text-right",
                      c.rate >= 80
                        ? "text-green-600"
                        : c.rate >= 50
                          ? "text-amber-600"
                          : "text-red-500",
                    )}
                  >
                    {c.rate}%
                  </span>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
